#|
  This file is a part of the Chorus project.
  Copyright (c) 2026 Christopher Mark Gore (cgore@cgore.com)
|#

(defpackage :chorus/cuda-libs
  (:use :cl)
  (:import-from :alexandria
                :format-symbol)
  (:export :load-cuda-library
           :*cublas-not-found*
           :*cublas-lt-not-found*
           :*cufft-not-found*
           :*curand-not-found*
           :*cusolver-not-found*
           :*cusparse-not-found*
           :*npp-not-found*
           :*nvjpeg-not-found*
           :*nccl-not-found*
           :*cudnn-not-found*
           :cublas-create
           :cublas-destroy
           :cublas-set-stream
           :cublas-sgemm
           :cublas-dgemm
           :cublas-saxpy
           :cublas-daxpy
           :cublas-sdot
           :cublas-ddot
           :cublas-sscal
           :cublas-dscal
           :cublas-lt-create
           :cublas-lt-destroy
           :cublas-lt-matmul-desc-create
           :cublas-lt-matmul-desc-destroy
           :cublas-lt-matmul-desc-set-attribute
           :cublas-lt-matrix-layout-create
           :cublas-lt-matrix-layout-destroy
           :cublas-lt-matmul
           :cublas-lt-matmul-algo-get-heuristic
           :+cufft-r2c+
           :+cufft-c2r+
           :+cufft-c2c+
           :+cufft-d2z+
           :+cufft-z2d+
           :+cufft-z2z+
           :+cufft-forward+
           :+cufft-inverse+
           :cufft-plan-1d
           :cufft-plan-2d
           :cufft-plan-3d
           :cufft-exec-c2c
           :cufft-exec-z2z
           :cufft-exec-r2c
           :cufft-exec-c2r
           :cufft-destroy
           :cufft-set-stream
           :+curand-rng-pseudo-default+
           :+curand-rng-pseudo-xorwow+
           :curand-create-generator
           :curand-destroy-generator
           :curand-set-stream
           :curand-set-pseudo-random-generator-seed
           :curand-generate-uniform
           :curand-generate-uniform-double
           :curand-generate-normal
           :curand-generate
           :cusolver-dn-create
           :cusolver-dn-destroy
           :cusolver-dn-set-stream
           :cusolver-dn-spotrf-buffer-size
           :cusolver-dn-spotrf
           :cusolver-dn-dpotrf-buffer-size
           :cusolver-dn-dpotrf
           :cusolver-dn-sgetrf-buffer-size
           :cusolver-dn-sgetrf
           :cusparse-create
           :cusparse-destroy
           :cusparse-spmv
           :cusparse-create-csr
           :cusparse-destroy-sp-mat
           :cusparse-create-dn-vec
           :cusparse-destroy-dn-vec
           :cusparse-create-dn-mat
           :cusparse-destroy-dn-mat
           :cusparse-spmm
           :npp-get-lib-version
           :nvjpeg-create-simple
           :nvjpeg-destroy
           :nvjpeg-get-image-info
           :nvjpeg-jpeg-state-create
           :nvjpeg-jpeg-state-destroy
           :+nccl-unique-id-bytes+
           :nccl-get-version
           :nccl-get-unique-id
           :nccl-comm-destroy
           :nccl-all-reduce
           :nccl-comm-count
           :cudnn-get-version
           :cudnn-create
           :cudnn-destroy
           :cudnn-create-tensor-descriptor
           :cudnn-destroy-tensor-descriptor
           :cudnn-set-tensor-4d-descriptor
           :cudnn-create-convolution-descriptor
           :cudnn-destroy-convolution-descriptor
           :cudnn-set-convolution-2d-descriptor
           :cudnn-convolution-forward))
